name: CI/CD for Angular App

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: npm run build -- --configuration=production
      
    - name: Deploy to hosting service
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/ng-medg-crm # Change 'your-project-name' to your actual project name
        publish_branch: gh-pages
        # cname: your-custom-domain.com # Optional: Add a custom domain if needed

    # Add further steps for testing, notifications, etc.
